# -*- coding: utf-8 -*-
"""Copy of Week 1 Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cevx4kCEbyKQeABML79glhmDteZ9Rf9w

#SQL

##Task 1
Query all columns for a city in CITY with the ID 1661.

Input Format

The CITY table is described as follows: <br>
<img src = "https://s3.amazonaws.com/hr-challenge-images/8137/1449729804-f21d187d0f-CITY.jpg">

1.   List item
2.   List item
"""

pd.read_sql_query('SELECT * FROM CITY WHERE ID=1661;', conn)

"""##Task 2
Query all columns for all American cities in CITY with populations larger than 100000. The CountryCode for America is USA.

Input Format<br>
<img src = "https://s3.amazonaws.com/hr-challenge-images/8137/1449729804-f21d187d0f-CITY.jpg">
"""

pd.read_sql_query('SELECT * FROM CITY WHERE POPULATION>100000 AND COUNTRYCODE="USA";', conn)

"""##Task 3
Query all attributes of every Japanese city in the CITY table. The COUNTRYCODE for Japan is JPN.

Input Format:<br>
<img src = "https://s3.amazonaws.com/hr-challenge-images/8137/1449729804-f21d187d0f-CITY.jpg">
"""

pd.read_sql_query('SELECT * FROM CITY WHERE COUNTRYCODE="JPN";', conn)

"""##Task 4
Query the names of all the Japanese cities in the CITY table. The COUNTRYCODE for Japan is JPN.

Input Format<br>
<img src = "https://s3.amazonaws.com/hr-challenge-images/8137/1449729804-f21d187d0f-CITY.jpg">
"""

pd.read_sql_query('SELECT NAME FROM CITY WHERE COUNTRYCODE="JPN";', conn)

"""##Task 5
Query a list of CITY and STATE from the STATION table.

Input Format

The STATION table is described as follows:<br>
<img src = 'https://s3.amazonaws.com/hr-challenge-images/9336/1449345840-5f0a551030-Station.jpg'>
"""

pd.read_sql_query('SELECT CITY, STATE FROM STATION;', conn)

"""##Task 6
Query a list of CITY names from STATION with even ID numbers only. You may print the results in any order, but must exclude duplicates from your answer.

Input Format

The STATION table is described as follows:<br>
<img src ="https://s3.amazonaws.com/hr-challenge-images/9336/1449345840-5f0a551030-Station.jpg">
"""

pd.read_sql_query('SELECT DISTINCT CITY FROM STATION WHERE MOD(ID, 2)=0;', conn)

"""Let  be the number of CITY entries in STATION, and let  be the number of distinct CITY names in STATION; query the value of  from STATION. In other words, find the difference between the total number of CITY entries in the table and the number of distinct CITY entries in the table.

Input Format

The STATION table is described as follows:<br>
<img src = "https://s3.amazonaws.com/hr-challenge-images/9336/1449345840-5f0a551030-Station.jpg"><br>
where LAT_N is the northern latitude and LONG_W is the western longitude.
"""

pd.read_sql_query('SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION;', conn)

"""##Task 7
Query the two cities in STATION with the shortest and longest CITY names, as well as their respective lengths (i.e.: number of characters in the name). If there is more than one smallest or largest city, choose the one that comes first when ordered alphabetically.

Input Format

The STATION table is described as follows:<br>
  <img src = "https://s3.amazonaws.com/hr-challenge-images/9336/1449345840-5f0a551030-Station.jpg">
"""

pd.read_sql_query('''SELECT * 
                     FROM (SELECT DISTINCT CITY, LENGTH(CITY) FROM STATION WHERE ROWNUM = 1 ORDER BY LENGTH(CITY) ASC, CITY ASC) 
                     UNION
                     SELECT * 
                     FROM (SELECT DISTINCT CITY, LENGTH(CITY) FROM STATION WHERE ROWNUM = 1 ORDER BY LENGTH(CITY) DESC, CITY ASC) ;
                  ''', conn)

"""##Task 8
Query the list of CITY names starting with vowels (i.e., a, e, i, o, or u) from STATION. Your result cannot contain duplicates.

Input Format

The STATION table is described as follows: <br>
<img src = "https://s3.amazonaws.com/hr-challenge-images/9336/1449345840-5f0a551030-Station.jpg" >
"""

pd.read_sql_query('SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE "A%" OR CITY LIKE "E%" OR CITY LIKE "I%" OR CITY LIKE "O%" OR CITY LIKE "U%";', conn)

"""##Task 9
Query the list of CITY names ending with vowels (a, e, i, o, u) from STATION. Your result cannot contain duplicates.

Input Format

The STATION table is described as follows:<br>
<img src ="https://s3.amazonaws.com/hr-challenge-images/9336/1449345840-5f0a551030-Station.jpg">
"""

pd.read_sql_query('SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE "%A" OR CITY LIKE "%E" OR CITY LIKE "%I" OR CITY LIKE "%O" OR CITY LIKE "%U";', conn)

"""##Task 10
Query the list of CITY names from STATION which have vowels (i.e., a, e, i, o, and u) as both their first and last characters. Your result cannot contain duplicates.

Input Format

The STATION table is described as follows:<br>
<img src ="https://s3.amazonaws.com/hr-challenge-images/9336/1449345840-5f0a551030-Station.jpg">
"""

pd.read_sql_query('''SELECT DISTINCT CITY 
                     FROM (SELECT DISTINCT CITY 
                           FROM STATION 
                           WHERE CITY LIKE "%A" 
                                 OR CITY LIKE "%E" 
                                 OR CITY LIKE "%I" 
                                 OR CITY LIKE "%O" 
                                 OR CITY LIKE "%U"
                           ) 
                     WHERE CITY LIKE "A%" 
                           OR CITY LIKE "E%" 
                           OR CITY LIKE "I%" 
                           OR CITY LIKE "O%" 
                           OR CITY LIKE "U%";
                  ''', conn)

"""#Python

##Task 1
Task
Given an integer, perform the following conditional actions:

* If n is odd, print `Weird`
* If n is even and in the inclusive range of 2 to 5, print `Not Weird`
* If n is even and in the inclusive range of 6 to 20, print `Weird`
* If n is even and greater than 20, print `Not Weird`

Input Format

A single line containing a positive integer

Output Format

Print Weird if the number is weird; otherwise, print Not Weird.
"""

if __name__ == '__main__':
    n = int(input())
    # your code here
    if n % 2 != 0:
      print('Weird')
    else:
      if 2 <= n <= 5:
        print('Not Weird')
      elif n <= 20:
        print('Weird')
      else: 
        print('Not Weird')

"""##Task 2
Read two integers from STDIN and print three lines where:
<ol>
  <li>The first line contains the sum of the two numbers.</li>
  <li>The second line contains the difference of the two numbers (first - second).</li>
  <li>The third line contains the product of the two numbers.</li>
</ol>

**Input Format**

The first line contains the first integer, **a**. The second line contains the second integer, **b**.

**Output Format**

Print the three lines as explained above.
"""

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    # your code here
    print(a+b)
    print(a-b)
    print(a*b)

"""#Task 3
Task
Read an integer $N$. For all non-negative integers $i<N$ , print $i^{2}$. See the sample for details.

Input Format

The first and only line contains the integer, $N$ .

Constraints<br>
$1 \leq N \leq i$

Output Format

Print $N$ lines, one corresponding to each $i$.
"""

if __name__ == '__main__':
    n = int(input())
    # your code here
    for i in range(n):
      print(i*i)

"""##Task 4
We add a Leap Day on February 29, almost every four years. The leap day is an extra, or intercalary day and we add it to the shortest month of the year, February.<br>

In the Gregorian calendar three criteria must be taken into account to identify leap years:
<ul>
<li>The year can be evenly divided by 4, is a leap year, unless:</li>
  <ul><li>The year can be evenly divided by 100, it is NOT a leap year, unless:</li>
    <ul><li>The year is also evenly divisible by 400. Then it is a leap year.</li></ul></ul></ul>
This means that in the Gregorian calendar, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years.Source

**Task**<br>
<ul>
<li>You are given the year, and you have to write a function to check if the year is leap or not.</li>

  <li>Note that you have to complete the function and remaining code is given as template.</li>
  </ul>

**Input Format**

Read y, the year that needs to be checked.

**Constraints**<br>
$1900 \leq y \leq 10^{5}$

**Output Format**

Output is taken care of by the template. Your function must return a boolean value (True/False)
"""

def is_leap(year):
  # your code here
  if year % 400 == 0:
    return True
  if year % 100 == 0:
    return False
  if year % 4 == 0:
    return True
  return False

print(is_leap(int(input())))

"""##Task 5
Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given $n$ scores. Store them in a list and find the score of the runner-up.

**Input Format**

The first line contains $n$ . The second line contains an array $A[]$ of $n$ integers each separated by a space.

**Constraints**<br>
$2   \leq n \leq 10 $<br>
$-100 \leq A[i] \leq 100 $

Output Format

Print the runner-up score.
"""

if __name__ == '__main__':
  n = int(input())
  # arr = input()
  # your code here
  scores = [int(x) for x in input().split()]
  first, second = scores[0], scores[1]
  for i in scores:
    if i > first:
      first, second = i, first
    elif i > second and i < first:
      second = i
  print(second)